sudo: required
services:
  - docker

before_install:
  - docker build -t ald3v/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ald3v/docker-react npm run test -- --coverage # -- --coverage to exit npm run test automatically
